name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Configure Git Safe Directory
        run: |
          ssh root@67.205.132.203 <<EOF
            git config --global --add safe.directory /var/www/staging.nofunmondays.com
          EOF
          
      - name: Pull latest code from staging
        run: |
          ssh root@67.205.132.203 <<'EOF'
            cd /var/www/staging.nofunmondays.com/
            git fetch --all
            git reset --hard origin/staging  # Hard reset to match the remote staging branch
            git clean -fd  # Remove any untracked files or directories
          EOF

      - name: Install dependencies for frontend
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/frontend
            npm install --legacy-peer-deps
          EOF

      - name: Build frontend
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/frontend
            npm run build  # Use build for production
          EOF

      - name: Start frontend with PM2
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/frontend
            pm2 start next --name "next-blue" -- start -p 3002
          EOF

      - name: Restart backend application
        run: |
          ssh root@67.205.132.203 <<EOF
            pm2 restart staging-app  # or replace with your backend restart command
          EOF

      - name: Restart Nginx reverse proxy
        run: |
          ssh root@67.205.132.203 <<EOF
            # Restart Nginx to apply the new frontend build
            sudo systemctl restart nginx
          EOF
