name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Cleanup Nginx and free disk space
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl stop nginx
            docker system prune -af --volumes
            sudo rm -rf /var/cache/nginx/*
            sudo rm -rf /var/log/nginx/*
            sudo rm -rf /tmp/*
            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            sudo systemctl start nginx
          EOF

      - name: Build frontend
        run: |
          cd frontend
          docker build --build-arg ENVIRONMENT=staging -t frontend .
          docker create --name frontend-container frontend
          docker cp frontend-container:/app/.next ./   # Copying to the current directory directly
          docker rm frontend-container
        
        

      - name: Upload frontend build files
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./frontend/.next

      - name: Install backend dependencies
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            npm install --legacy-peer-deps
          EOF

      - name: Restart backend application
        run: |
          ssh root@67.205.132.203 <<EOF
            pm2 restart staging-app || pm2 start /var/www/staging.nofunmondays.com/backend/app.js --name staging-app
          EOF

      - name: Download frontend build files to server
        uses: actions/download-artifact@v3
        with:
          name: frontend-build

      - name: Copy frontend build to DigitalOcean server
        run: |
          ssh root@67.205.132.203 <<EOF
            rm -rf /var/www/staging.nofunmondays.com/frontend/.next/*
            cp -r $(pwd)/frontend/.next/* /var/www/staging.nofunmondays.com/frontend/.next/
          EOF

      - name: Restart Nginx
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl restart nginx
          EOF
