name: Deploy to Staging

on:
  push:
    branches:
      - staging  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Pull orgin from staging
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/
            git pull origin staging
          EOF

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Install dependencies for backend
        run: |
          npm install --legacy-peer-deps

      - name: Configure Git Safe Directory
        run: |
          ssh root@67.205.132.203 <<EOF
            git config --global --add safe.directory /var/www/nofunmondays.com/backend
          EOF

      - name: Deploy frontend to production server
        run: |
          npm run build

      - name: Deploy backend to production server
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            pm2 restart staging-app  # Or whatever your production app is named
          EOF
