name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Pull latest code from main
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/nofunmondays.com/
            if [ ! -d .git ]; then
              git fetch --all
              git reset --hard origin/main
              git clean -fd
              git checkout main
            else
              git pull origin main
            fi
          EOF

      - name: Build frontend
        run: |
          ssh root@67.205.132.203 <<EOF
            docker rm -f frontend || true
            docker build -t frontend /var/www/nofunmondays.com/frontend
            docker run -d -p 3000:3000 --name frontend frontend
          EOF

      - name: Install backend dependencies
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/nofunmondays.com/backend
            npm install --legacy-peer-deps
          EOF

      - name: Restart backend application
        run: |
          ssh root@67.205.132.203 <<EOF
            pm2 restart production-app || pm2 start /var/www/production.nofunmondays.com/backend/app.js --name production-app
          EOF

      - name: Restart Nginx
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl restart nginx
          EOF