name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build --build-arg ENVIRONMENT=staging -t frontend .

      - name: Save frontend Docker image to a tar file
        run: |
          docker save frontend -o frontend.tar

      - name: Upload Docker image to the server
        run: |
          scp frontend.tar root@67.205.132.203:/var/www/staging.nofunmondays.com/frontend.tar

      - name: Extract and run the Docker container on the server.
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com
            tar -xvf frontend.tar
            rm frontend.tar
            docker run -d -p 3002:3000 frontend
          EOF

      - name: Install backend dependencies
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            npm install --legacy-peer-deps
          EOF

      - name: Restart backend application
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com
            if pm2 list | grep -q 'app-blue'; then
              pm2 restart app-blue
            else
              pm2 start npm --name app-blue -- start
            fi
          EOF

      - name: Restart Nginx
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl restart nginx
          EOF
