name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Configure Git Safe Directory
        run: |
          ssh root@67.205.132.203 <<EOF
            git config --global --add safe.directory /var/www/staging.nofunmondays.com
          EOF
          
      - name: Pull latest code from staging
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/
            git fetch --all
            git reset --hard origin/staging  # Hard reset to match the remote staging branch
            git clean -fd  # Remove any untracked files or directories
            EOF

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Build frontend
        run: |
          cd frontend
          npm run build  # Use build for production, not start

      - name: Deploy frontend build to staging server
        run: |
          scp -r frontend/build/* root@67.205.132.203:/var/www/staging.nofunmondays.com/frontend/build

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install --legacy-peer-deps

      - name: Restart backend application
        run: |
          ssh root@67.205.132.203 <<EOF
            # Restart the backend (e.g., using pm2 or systemctl)
            pm2 restart staging-app  # or replace with your backend restart command

      - name: Start frontend with PM2.
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/frontend
            pm2 start npm --name "frontend" -- run start 
          EOF

      - name: Restart frontend server (Nginx reverse proxy)
        run: |
          ssh root@67.205.132.203 <<EOF
            # Restart Nginx to apply new frontend build
            sudo systemctl restart nginx
          EOF