name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Pull latest code from staging
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/
            git fetch --all
            git reset --hard origin/staging
            git clean -fd
          EOF

      - name: Build Docker image
        run: |
          docker build -t staging-app .
          docker save staging-app | gzip > staging-app.tar.gz

      - name: Transfer Docker image
        run: |
          scp staging-app.tar.gz root@67.205.132.203:/tmp/

      - name: Deploy Docker image and run
        run: |
          ssh root@67.205.132.203 <<EOF
            gzip -d /tmp/staging-app.tar.gz
            docker load < /tmp/staging-app.tar
            docker rm -f staging-app || true
            docker run -d -p 3002:3000 --name staging-app staging-app
          EOF

      - name: Install backend dependencies
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            npm install --legacy-peer-deps
          EOF

      - name: Restart backend application
        run: |
          ssh root@67.205.132.203 <<EOF
            pm2 restart staging-app || pm2 start /var/www/staging.nofunmondays.com/backend/app.js --name staging-app
          EOF

      - name: Restart Nginx
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl restart nginx
          EOF
