name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install --legacy-peer-deps

      - name: Configure Git Safe Directory
        run: |
          ssh root@67.205.132.203 <<EOF
            git config --global --add safe.directory /var/www/nofunmondays.com/backend
          EOF
          
      - name: Deploy frontend to staging server
        run: |
          scp -r frontend/build/* root@67.205.132.203:/var/www/staging.nofunmondays.com/frontend/frontend/build

      - name: Deploy backend to staging server
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            git pull origin main
            npm install --legacy-peer-deps
            pm2 restart staging-app
          EOF
