name: Deploy to Staging

on:
  push:
    branches:
      - staging  # Set the branch to deploy from, e.g., main or staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install --legacy-peer-deps

      - name: Deploy backend to staging server
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            git pull origin main
            npm install --legacy-peer-deps
            pm2 restart production-app
          EOF
