name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Cleanup Nginx and free disk space
        run: |
          ssh root@67.205.132.203 <<EOF
            # Stop Nginx
            sudo systemctl stop nginx
            
            # Remove unused Docker containers, images, and volumes
            docker system prune -af --volumes
            
            # Clear Nginx temporary files
            sudo rm -rf /var/cache/nginx/*
            sudo rm -rf /var/log/nginx/*
            
            # Clean up system temporary files
            sudo rm -rf /tmp/*
            
            # Free up apt cache
            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            
            # Restart Nginx
            sudo systemctl start nginx
          EOF

      - name: Pull latest code from staging
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/
            git fetch --all
            git reset --hard origin/staging  # Hard reset to match the remote staging branch
            git clean -fd  # Remove any untracked files or directories
          EOF

      - name: Build frontend
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/frontend
            docker build --build-arg ENVIRONMENT=staging -t frontend /var/www/staging.nofunmondays.com/frontend
            docker run -d -p 3002:3000 --name frontend-staging frontend
          EOF

      - name: Install backend dependencies
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            npm install --legacy-peer-deps
          EOF

          - name: Restart backend application
          run: |
            ssh root@67.205.132.203 <<EOF
              pm2 restart app-green ||pm2 start npm --name app-green -- start

            EOF
        

      - name: Restart Nginx
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl restart nginx
          EOF