name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts

      - name: Pull latest code from staging
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/
            git fetch --all
            git reset --hard origin/staging
            git clean -fd
          EOF

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t docker-blue .
          docker save docker-blue | gzip > $GITHUB_WORKSPACE/docker-blue.tar.gz

      - name: Check if the tar.gz file exists
        run: |
          ls -l $GITHUB_WORKSPACE/docker-blue.tar.gz

      - name: Transfer Docker image
        run: |
          scp $GITHUB_WORKSPACE/docker-blue.tar.gz root@67.205.132.203:/tmp/

      - name: Deploy Docker image and run
        run: |
          ssh root@67.205.132.203 <<EOF
            gzip -d /tmp/docker-blue.tar.gz
            docker load < /tmp/docker-blue.tar
            docker rm -f docker-blue || true
            docker run -d -p 3002:3000 --name docker-blue docker-blue
          EOF

      - name: Install backend dependencies
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            npm install --legacy-peer-deps
          EOF

      - name: Restart backend application
        run: |
          ssh root@67.205.132.203 <<EOF
            pm2 restart docker-blue || pm2 start /var/www/staging.nofunmondays.com/backend/app.js --name docker-blue
          EOF

      - name: Restart Nginx
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl restart nginx
          EOF
