name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.0.0'  

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install --legacy-peer-deps

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 67.205.132.203 >> ~/.ssh/known_hosts || exit 0

      - name: Pull latest code on server
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com
            git reset --hard
            git pull origin staging
          EOF

      - name: Deploy frontend
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./frontend/build/ root@67.205.132.203:/var/www/staging.nofunmondays.com/frontend/build/
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./frontend/public/ root@67.205.132.203:/var/www/staging.nofunmondays.com/frontend/public/

      - name: Deploy backend
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./backend/ root@67.205.132.203:/var/www/staging.nofunmondays.com/backend/

      - name: Start frontend with PM2
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/frontend
            pm2 describe "next-blue" > /dev/null || pm2 start npm --name "next-blue" -- run start:blue
            pm2 restart "next-blue" || true
          EOF
      
      - name: Start backend with PM2
        run: |
          ssh root@67.205.132.203 <<EOF
            cd /var/www/staging.nofunmondays.com/backend
            pm2 describe "backend-blue" > /dev/null || pm2 start npm --name "backend-blue" -- run start:blue
            pm2 restart "backend-blue" || true
          EOF
        
      - name: Restart Nginx reverse proxy
        run: |
          ssh root@67.205.132.203 <<EOF
            sudo systemctl restart nginx
          EOF
